"""Generic constraint-satisfaction algorithms."""

from proyek_certan.constraint_solver.ac3 import (
    AC3Result,
    AC3Stats,
    ReviseResult,
    ac3,
    revise,
)
from proyek_certan.constraint_solver.backtracking import (
    BacktrackingResult,
    BacktrackingStats,
    ForwardCheckResult,
    backtracking_search,
    forward_check,
    is_consistent,
    order_domain_values,
    select_unassigned_variable,
)
from proyek_certan.constraint_solver.csp import CSP, ConstraintFunction
from proyek_certan.constraint_solver.incident_assignment import (
    AssignmentValue,
    IncidentAssignmentResult,
    SolutionValidation,
    Technician,
    build_domains,
    build_incident_assignment_csp,
    build_neighbors,
    load_technicians,
    solve_incident_assignment,
    solve_incident_assignment_files,
    technician_slot_different,
    validate_solution,
    validate_technicians,
)
from proyek_certan.constraint_solver.solver import (
    SolverResult,
    SolverStats,
    SolverStatus,
    solve,
)

__all__ = [
    "AC3Result",
    "AC3Stats",
    "AssignmentValue",
    "BacktrackingResult",
    "BacktrackingStats",
    "CSP",
    "ConstraintFunction",
    "ForwardCheckResult",
    "IncidentAssignmentResult",
    "ReviseResult",
    "SolutionValidation",
    "SolverResult",
    "SolverStats",
    "SolverStatus",
    "Technician",
    "ac3",
    "backtracking_search",
    "build_domains",
    "build_incident_assignment_csp",
    "build_neighbors",
    "forward_check",
    "is_consistent",
    "load_technicians",
    "order_domain_values",
    "revise",
    "select_unassigned_variable",
    "solve",
    "solve_incident_assignment",
    "solve_incident_assignment_files",
    "technician_slot_different",
    "validate_solution",
    "validate_technicians",
]
